### ISSUE TITLE
Feature request: wait before trying to re-login

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#11]
It would be nice to have a configurabile delay between login requests so that we can use the mobile app in a pinch while the MQTT gateway is running.

**Comment by tosate** [comment]
The feature is implemented in the develop branch. would you be able to test it?

**Comment by nanomad** [comment]
Will do!

I've closed by PR

**Comment by nanomad** [comment]
Looks like there's a missing type cast whe configuring the feature via env variabile:

```
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 725, in <module>
    mqtt_gateway.run()
  File "/usr/src/app/./mqtt_gateway.py", line 451, in run
    asyncio.run(main(self.vehicle_handler, message_handler, self.configuration.messages_request_interval))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/src/app/./mqtt_gateway.py", line 623, in main
    await task
  File "/usr/src/app/./mqtt_gateway.py", line 208, in handle_vehicle
    vehicle_status = self.update_vehicle_status()
  File "/usr/src/app/./mqtt_gateway.py", line 251, in update_vehicle_status
    vehicle_status_rsp_msg = self.saic_api.get_vehicle_status_with_retry(self.vin_info)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 181, in get_vehicle_status_with_retry
    return self.handle_retry(self.get_vehicle_status, vin_info)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 427, in handle_retry
    self.handle_error(rsp_msg.body)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 612, in handle_error
    if self.relogin_delay > 0:

```
