### ISSUE TITLE
charging_stations.json socTopic could be optional

### ISSUE THREAD

**Issue by denisfrench** [SAIC-iSmart-API/saic-python-mqtt-gateway#123]
My OpenEVSE happily directly subscribes to ```saic/<REDACTED>/vehicles/LSJ<REDACTED>/drivetrain/soc``` where the gateway publishes to by default, therefore ```socTopic``` within charging_stations.json is redundant for me.

Omitting ```socTopic``` from charging_stations.json throws an error halting the addon, so I have entered one, but this is unneccessary MQTT traffic.

Mostly harmless I guess, but ```socTopic``` could be made optional in a future release.

Thanks for everyone's work on this 🙂

**Comment by tosate** [comment]
The SoC topic is essential for openWB and this is how the logic is implemented. I will make the socTopci field in the charging station configuration optional.

**Comment by kiss81** [comment]
I do get this now:
`
2024-01-02 10:12:07,276 [WARNING ] File ./charging-stations.json does not exist - __main__
2024-01-02 10:12:07,748 [  INFO  ] Connected to MQTT broker - mqtt_publisher
2024-01-02 10:12:07,751 [  INFO  ] Scheduler started - apscheduler.scheduler
2024-01-02 10:12:08,043 [  INFO  ] Registering for abnormal messages - __main__
2024-01-02 10:12:08,180 [  INFO  ] Registering for moving messages - __main__
2024-01-02 10:12:08,331 [  INFO  ] Registering for region messages - __main__
2024-01-02 10:12:08,496 [  INFO  ] Registering for engineStart messages - __main__
2024-01-02 10:12:08,651 [  INFO  ] Registering for startVehicleStatus messages - __main__
2024-01-02 10:12:08,812 [  INFO  ] Registering for offCar messages - __main__
2024-01-02 10:12:08,950 [  INFO  ] Registering for speeding messages - __main__
Traceback (most recent call last):
  File "/root/saic-python-mqtt-gateway/mqtt_gateway.py", line 714, in <module>
    asyncio.run(mqtt_gateway.run(), debug=debug_log_enabled())
  File "/root/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.3/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/saic-python-mqtt-gateway/mqtt_gateway.py", line 319, in run
    if charging_station.soc_topic:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'soc_topic'
`

**Comment by tosate** [comment]
Thanks for testing @kiss81 ! Should be fine again.

**Comment by marsflow2** [comment]
Hi,

What did you write in your charging-stations.json file for openevse?


[
    {
        "chargeStateTopic": "openevse/status",
        "chargingValue": "active",
        //"socTopic": "openevse/battery_level",
        "chargerConnectedTopic": "openevse/vehicle",
        "chargerConnectedValue": "1",
        "vin": "my-vin-car"
    }
]
I don't have a refresh when I charge the car

**Comment by denisfrench** [comment]
Hi @marsflow2;

I experimented with a few different topics published from OpenEVSE. The one that best indicates actual charging (as opposed to sleeping etc) is when ```openevse/state == 3```.

Thus my charging-stations.json is:
```
[
    {
        "chargeStateTopic": "openevse/state",
        "chargingValue": "3",
        "chargerConnectedTopic": "openevse/vehicle",
        "chargerConnectedValue": "1",
        "vin": "LSJ<REDACTED>"
    }
]
```

_However_; beware that for my MG4 when a charge limit is set within the MG iSmart app/car, a race condition resulting in rapid (15-30s) cycling the OpenEVSE on and off occurred whenever the car awoke and was already at the charge limit. I think the car awoke and commenced charging, then realised the limit was reached and switched off. Meanwhile OpenEVSE changed the ```openevse/state``` flag, causing the MQTT gateway to refresh, awakening the car again, and the cycle continued.

Hence I no longer use charging-stations.yaml to cause an automatic refresh, instead implementing the logic within a Home Assistant automation but with a 10s delay to avoid the race condition.

Hi @tosate; I have not had a chance to fully troubleshoot and raise an issue, partly because I first need to confirm my region (au) works with the new API endpoint. Checking that the state has changed for at least 10s (using HA automations) between state change and force refresh of the gateway is working for me to avoid the race condition on version 0.4.6 . I realise this is more a problem with the clunky MG charging logic than your gateway 😕
