### ISSUE TITLE
he account has been locked, please try again tomorrow or you may reset password by clicking not working 

### ISSUE THREAD

**Issue by kohbi** [SAIC-iSmart-API/saic-python-mqtt-gateway#129]
hey after app upgrade to V2.0.3  login on app work fine ... but the gateway  ... error ...
saic-mqtt-gateway    | 2024-01-17 10:48:37,841 [ DEBUG  ] Calculated message siz                                                                                                             e 264 does not match with header size information 8. Using calculated size. - sa                                                                                                             ic_ismart_client.common_model
saic-mqtt-gateway    | 2024-01-17 10:48:37,843 [ ERROR  ] MqttGateway crashed du                                                                                                             e to SaicApiException - __main__
saic-mqtt-gateway    | Traceback (most recent call last):
saic-mqtt-gateway    |   File "/usr/src/app/./mqtt_gateway.py", line 301, in run
saic-mqtt-gateway    |     login_response_message = self.saic_api.login()
saic-mqtt-gateway    |                              ^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_isma                                                                                                             rt_client/saic_api.py", line 122, in login
saic-mqtt-gateway    |     raise SaicApiException(login_response_message.body.er                                                                                                             ror_message,
saic-mqtt-gateway    | saic_ismart_client.exceptions.SaicApiException: return co                                                                                                             de: 15033, message: Sorry, the account has been locked, please try again tomorro                                                                                                             w or you may reset password by clicking “forget password”if you forget it.
saic-mqtt-gateway    | 2024-01-17 10:48:37,856 [ DEBUG  ] Looking for jobs to ru                                                                                                             n - apscheduler.scheduler
saic-mqtt-gateway    | 2024-01-17 10:48:37,860 [ DEBUG  ] No jobs; waiting until                                                                                                              a job is added - apscheduler.scheduler
saic-mqtt-gateway    | return code: 15033, message: Sorry, the account has been                                                                                                              locked, please try again tomorrow or you may reset password by clicking “forget                                                                                                              password”if you forget it.

**Comment by nanomad** [comment]
This is due to the new app coming out. Recovery steps:
1. Stop the current MQTT gateway
2. Log-in into the app, if the login doesn't work do a password reset. Remember to use only letter and numbers
3. Start the MQTT Gateway, version 0.5.1 or later as it uses the new APIs

**Comment by kohbi** [comment]
Hey, 

is that Version avalible as docker Imsge ?

**Comment by nanomad** [comment]
@kohbi it is
