### ISSUE TITLE
Commands not going through

### ISSUE THREAD

**Issue by kimtatti** [SAIC-iSmart-API/saic-python-mqtt-gateway#140]
Sensor values update normally and by force, but cannot set remote heating on, control charging or anything else.
iSmart app works normally. Problems started when updated iSmart to V2.0.4 on iphone.

**Comment by fredrikjohnsson** [comment]
I have the exact same issue. Home Assistant add-on log gives the following when trying to activate the heating:

`2024-01-28 20:43:43,232 [ ERROR  ] application ID: 510, protocol version: 25857, message: The service is not available,please try again later~ result code: 702 - saic_ismart_client.saic_api
2024-01-28 20:43:43,233 [ ERROR  ] return code: 702, message: The service is not available,please try again later~ - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 179, in handle_mqtt_command
    self.saic_api.start_front_defrost(self.vin_info)
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 285, in start_front_defrost
    return self.control_climate(vin_info, fan_speed=5, ac_on=True, temperature_idx=8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 351, in control_climate
    return self.send_vehicle_ctrl_cmd_with_retry(vin_info, b'\x06', rcv_params, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 438, in send_vehicle_ctrl_cmd_with_retry
    return self.handle_retry(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 457, in handle_retry
    return self.__handle_retry_with_app_data(func, vin_info=vin_info, max_retries=max_retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 501, in __handle_retry_with_app_data
    self.handle_error(rsp_msg.body, iteration)
  File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 880, in handle_error
    raise SaicApiException(message_body.error_message, message_body.result)
saic_ismart_client.exceptions.SaicApiException: return code: 702, message: The service is not available,please try again later~`

**Comment by Tonno87** [comment]
Update to 0.5.1 is out. Seems to be a problem with the old api.

**Comment by nanomad** [comment]
Feel free to re-open the ticket after updating to 0.5.x if needed, keep in mind errors still happen on the server end
