### ISSUE TITLE
code: 702, message: The service is not available,please try again later

### ISSUE THREAD

**Issue by bj00rn** [SAIC-iSmart-API/saic-python-mqtt-gateway#145]
Commands to api fail with below error

```
saic-mqtt-gateway    | 2024-01-30 14:03:02,180 [  INFO  ] A/C will be switched on - __main__
saic-mqtt-gateway    | 2024-01-30 14:03:02,449 [ DEBUG  ] Message length in bytes: 192.0 - saic_ismart_client.common_model
saic-mqtt-gateway    | 2024-01-30 14:03:02,449 [ DEBUG  ] Protocol version: 33 - saic_ismart_client.common_model
saic-mqtt-gateway    | 2024-01-30 14:03:02,449 [ DEBUG  ] Dispatcher message length: 176 - saic_ismart_client.common_model
saic-mqtt-gateway    | 2024-01-30 14:03:02,450 [ DEBUG  ] Message size without header and reserved bytes: 173.0 - saic_ismart_client.common_model
saic-mqtt-gateway    | 2024-01-30 14:03:02,450 [ DEBUG  ] Dispatcher message bytes: 173 - saic_ismart_client.common_model
saic-mqtt-gateway    | 2024-01-30 14:03:02,452 [ ERROR  ] application ID: 510, protocol version: 25857, message: The service is not available,please try again later~ result code: 702 - saic_ismart_client.saic_api
saic-mqtt-gateway    | 2024-01-30 14:03:02,453 [ ERROR  ] return code: 702, message: The service is not available,please try again later~ - __main__
saic-mqtt-gateway    | Traceback (most recent call last):
saic-mqtt-gateway    |   File "/usr/src/app/./mqtt_gateway.py", line 175, in handle_mqtt_command
saic-mqtt-gateway    |     self.saic_api.start_ac(self.vin_info,
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 276, in start_ac
saic-mqtt-gateway    |     return self.control_climate(vin_info, fan_speed=2, ac_on=None, temperature_idx=temperature_idx)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 351, in control_climate
saic-mqtt-gateway    |     return self.send_vehicle_ctrl_cmd_with_retry(vin_info, b'\x06', rcv_params, True)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 438, in send_vehicle_ctrl_cmd_with_retry
saic-mqtt-gateway    |     return self.handle_retry(
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 457, in handle_retry
saic-mqtt-gateway    |     return self.__handle_retry_with_app_data(func, vin_info=vin_info, max_retries=max_retries)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 501, in __handle_retry_with_app_data
saic-mqtt-gateway    |     self.handle_error(rsp_msg.body, iteration)
saic-mqtt-gateway    |   File "/usr/local/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 880, in handle_error
saic-mqtt-gateway    |     raise SaicApiException(message_body.error_message, message_body.result)
saic-mqtt-gateway    | saic_ismart_client.exceptions.SaicApiException: return code: 702, message: The service is not available,please try again later~
```

**Comment by tosate** [comment]
Please use the latest version of the gateway that uses the saic-ismart-client-ng module. It uses the new SAIC API. Re-open the ticket if the error persists.
