### ISSUE TITLE
Trying to turn heating on in MG5 LR

### ISSUE THREAD

**Issue by waroen** [SAIC-iSmart-API/saic-python-mqtt-gateway#165]
When trying to activate the climate system to pre-heat the car the following error occurs constantly.

2024-02-08 00:20:23,696 [ ERROR  ] return code: 8, message: The remote control instruction failed, please try again later.(255) - __main__
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 206, in handle_mqtt_command
    await self.saic_api.start_front_defrost(self.vin_info.vin)
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/vehicle/climate/__init__.py", line 44, in start_front_defrost
    return await self.control_climate(vin, fan_speed=5, ac_on=True, temperature_idx=8)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/vehicle/climate/__init__.py", line 78, in control_climate
    return await self.send_vehicle_control_command(body, vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/vehicle/__init__.py", line 27, in send_vehicle_control_command
    return await self.execute_api_call_with_event_id(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 124, in execute_api_call_with_event_id
    return await execute_api_call_with_event_id_inner(event_id='0')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 115, in execute_api_call_with_event_id_inner
    return await self.execute_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 92, in execute_api_call
    return await self.deserialize(req, response, out_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 185, in deserialize
    raise se
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 161, in deserialize
    raise SaicApiRetryException(
saic_ismart_client_ng.exceptions.SaicApiRetryException: return code: 8, message: The remote control instruction failed, please try again later.(255), event_id: 1999899379

I have no idea what goes wrong but hopefully someone can shed some light on this error.

**Comment by kimtatti** [comment]
Same error occures in the iSmart app when my MG5 is charging. Charging has to be disabled and then climate can be activated. Could it be that?

**Comment by nanomad** [comment]
> Same error occures in the iSmart app when my MG5 is charging. Charging has to be disabled and then climate can be activated. Could it be that?

I've seen that happen randomly, the app doesn't have an explicit interlock as far as I know...
