### ISSUE TITLE
Problem into Jeedom installation

### ISSUE THREAD

**Issue by hudsson** [SAIC-iSmart-API/saic-python-mqtt-gateway#198]
I try to connect my MG4 with my Jeedom.
MQTT is ok with Mosquitto config

I use Docker Management to create my docker's car
but I've message error in the logs

`2024-03-29T10:11:04.412109787Z Traceback (most recent call last):
2024-03-29T10:11:04.424805654Z   File "/usr/src/app/./mqtt_gateway.py", line 878, in 
2024-03-29T10:11:04.424882477Z     mqtt_gateway = MqttGateway(configuration)
2024-03-29T10:11:04.424917997Z                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.424951800Z   File "/usr/src/app/./mqtt_gateway.py", line 400, in __init__
2024-03-29T10:11:04.424985602Z     self.publisher = MqttClient(self.configuration)
2024-03-29T10:11:04.425018935Z                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.425052112Z   File "/usr/src/app/publisher/mqtt_publisher.py", line 44, in __init__
2024-03-29T10:11:04.427208828Z     mqtt_client = gmqtt.Client(
2024-03-29T10:11:04.428961638Z                   ^^^^^^^^^^^^^
2024-03-29T10:11:04.429088408Z   File "/usr/local/lib/python3.12/site-packages/gmqtt/client.py", line 155, in __init__
2024-03-29T10:11:04.432720226Z     self._resend_task = asyncio.ensure_future(self._resend_qos_messages())
2024-03-29T10:11:04.432834028Z                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.432870017Z   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 693, in ensure_future
2024-03-29T10:11:04.437233657Z     loop = events.get_event_loop()
2024-03-29T10:11:04.437652042Z            ^^^^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.438952925Z   File "/usr/local/lib/python3.12/asyncio/events.py", line 699, in get_event_loop
2024-03-29T10:11:04.443083180Z     self.set_event_loop(self.new_event_loop())
2024-03-29T10:11:04.444048283Z                         ^^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.444307970Z   File "/usr/local/lib/python3.12/asyncio/events.py", line 720, in new_event_loop
2024-03-29T10:11:04.446932653Z     return self._loop_factory()
2024-03-29T10:11:04.447616090Z            ^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.448807859Z   File "/usr/local/lib/python3.12/asyncio/unix_events.py", line 64, in __init__
2024-03-29T10:11:04.451723688Z     super().__init__(selector)
2024-03-29T10:11:04.452063427Z   File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 60, in __init__
2024-03-29T10:11:04.454785715Z     super().__init__()
2024-03-29T10:11:04.454935507Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 421, in __init__
2024-03-29T10:11:04.459044615Z     self._clock_resolution = time.get_clock_info('monotonic').resolution
2024-03-29T10:11:04.468636164Z                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.468799341Z PermissionError: [Errno 1] Operation not permitted
2024-03-29T10:11:04.536511692Z Exception ignored in: 
2024-03-29T10:11:04.536640337Z Traceback (most recent call last):
2024-03-29T10:11:04.536675598Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 724, in __del__
2024-03-29T10:11:04.539383927Z     _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
2024-03-29T10:11:04.539909551Z                                 ^^^^^^^^
2024-03-29T10:11:04.539984916Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 443, in __repr__
2024-03-29T10:11:04.542232517Z     f'closed={self.is_closed()} debug={self.get_debug()}>'
2024-03-29T10:11:04.542748818Z                                        ^^^^^^^^^^^^^^^^
2024-03-29T10:11:04.542837672Z   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 2004, in get_debug
2024-03-29T10:11:04.553487449Z     return self._debug
2024-03-29T10:11:04.559391555Z            ^^^^^^^^^^^
2024-03-29T10:11:04.559491919Z AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
2024-03-29T10:11:04.559559992Z sys:1: RuntimeWarning: coroutine 'Client._resend_qos_messages' was never awaited`

Can you help me please ?

**Comment by tosate** [comment]
Hi @hudsson,

there seems to be an issue with your docker installation [as you can read in this issue](https://github.com/freqtrade/freqtrade/issues/6183)

Updating your installation might work: `sudo apt update && sudo apt upgrade`

Can you please provide the output of the following command: `uname -a`

There should be something like:
```
Linux tools 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

**Comment by hudsson** [comment]
Hi, thank you for your help.
I've made updating

the command uname -a 
`Linux jeedom 5.10.103-v7+ #1529 SMP Tue Mar 8 12:21:37 GMT 2022 armv7l GNU/Linux`
