### ISSUE TITLE
Feature: Window status entities should be a sensor and not a switch on models that do not support remote windows control

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#252]

**Comment by bj00rn** [comment]
I second this. Toggling switches gives error:

```
saic-mqtt-gateway    | Traceback (most recent call last):
saic-mqtt-gateway    |   File "/usr/src/app/./mqtt_gateway.py", line 391, in handle_mqtt_command
saic-mqtt-gateway    |     await self.vehicle_state.configure_by_message(topic=topic, payload=payload)
saic-mqtt-gateway    |   File "/usr/src/app/vehicle.py", line 579, in configure_by_message
saic-mqtt-gateway    |     raise MqttGatewayException(f'Unsupported topic {topic}')
saic-mqtt-gateway    | exceptions.MqttGatewayException: Unsupported topic windows/sunRoof
```

**Comment by nanomad** [comment]
Fixed in 0.11.0
