### ISSUE TITLE
Can't connect to Mosquitto

### ISSUE THREAD

**Issue by billouetaudrey** [SAIC-iSmart-API/saic-python-mqtt-gateway#269]
Hi, can you help me please ?

Saic logs : 
> 2024-10-11 08:21:45,248 [  INFO  ] Logging in to SAIC API - __main__
> 2024-10-11 08:21:47,555 [  INFO  ] Logged in as *** - __main__
> 2024-10-11 08:21:47,555 [  INFO  ] Fetching vehicle list - __main__
> 2024-10-11 08:21:47,680 [  INFO  ] Registering for ['ALARM_TYPE_VEHICLE_FAULT', 'ALARM_TYPE_GEOFENCE', 'ALARM_TYPE_VEHICLE_START'] messages. vin=*** - __main__
> 2024-10-11 08:21:47,760 [  INFO  ] Registered for ['ALARM_TYPE_VEHICLE_FAULT', 'ALARM_TYPE_GEOFENCE', 'ALARM_TYPE_VEHICLE_START'] messages. vin=*** - __main__
> 2024-10-11 08:21:47,793 [  INFO  ] Adding job tentatively -- it will be properly scheduled when the scheduler starts - apscheduler.scheduler
> Traceback (most recent call last):
>   File "/usr/src/app/./mqtt_gateway.py", line 941, in <module>
>     asyncio.run(mqtt_gateway.run(), debug=debug_log_enabled())
>   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/usr/src/app/./mqtt_gateway.py", line 506, in run
>     await self.publisher.connect()
>   File "/usr/src/app/publisher/mqtt_publisher.py", line 86, in connect
>     await self.client.connect(host=self.host, port=self.port, version=gmqtt.constants.MQTTv311, ssl=ssl_context)
>   File "/usr/local/lib/python3.12/site-packages/gmqtt/client.py", line 225, in connect
>     self._connection = await self._create_connection(
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/gmqtt/client.py", line 241, in _create_connection
>     connection = await MQTTConnection.create_connection(host, port, ssl, clean_session, keepalive, logger=self._logger)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/site-packages/gmqtt/mqtt/connection.py", line 27, in create_connection
>     transport, protocol = await loop.create_connection(MQTTProtocol, host, port, ssl=ssl)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1129, in create_connection
>     raise OSError('Multiple exceptions: {}'.format(
> OSError: Multiple exceptions: [Errno 111] Connect call failed ('::1', 1883, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 1883)
> 2024-10-11 08:21:47,817 [ ERROR  ] Task was destroyed but it is pending!
> task: <Task pending name='Task-1' coro=<Client._resend_qos_messages() running at /usr/local/lib/python3.12/site-packages/gmqtt/client.py:176>> - asyncio
> sys:1: RuntimeWarning: coroutine 'Client._resend_qos_messages' was never awaited

Mosquitto logs :
> 1728634695: mosquitto version 2.0.19 starting
> 1728634695: Config loaded from /mosquitto/config/mosquitto.conf.
> 1728634695: Warning: File /mosquitto/config/pwfile has world readable permissions. Future versions will refuse to load this file.
> To fix this, use `chmod 0700 /mosquitto/config/pwfile`.
> 1728634695: Opening ipv4 listen socket on port 1883.
> 1728634695: Opening ipv6 listen socket on port 1883.
> 1728634695: Opening websockets listen socket on port 9001.
> 1728634695: mosquitto version 2.0.19 running
> 1728634699: New connection from 192.168.1.48:43711 on port 1883.
> 1728634699: New client connected from 192.168.1.48:43711 as 37pyf6yiQfo3WLmhbTEqFk (p2, c1, k60, u'billou').
> 

Docker-compose file : 

```
version: "3.1"

services:
  saic-mqtt-gateway:
    image: "saicismartapi/saic-python-mqtt-gateway:latest"
    container_name: "saic-mqtt-gateway"
    environment:
      - MQTT_URI=tcp://localhost:1883
      - MQTT_USER=***
      - MQTT_PASSWORD=***
      - SAIC_USER=***
      - SAIC_PASSWORD=***
    volumes:
      - ./charging-stations.json:/usr/src/app/charging-stations.json
```

Thanks very much

**Comment by billouetaudrey** [comment]
Sorry fixed

change localhost by local ip ;)
