### ISSUE TITLE
How to add VIN to ABRP

### ISSUE THREAD

**Issue by billouetaudrey** [SAIC-iSmart-API/saic-python-mqtt-gateway#280]
Hello,

How to add VIN to ABRP please ?

Thanks

**Comment by aneantisor** [comment]
Hello,

I'm trying to get abrp working. it looks like --abrp-user-token is not working.
i tried to debug the code, finaly, i've hardcoded the token in integration/abrp/api.py and then it work.
maybe there is a problem with the way vin=token is splitted ?

i keep searching but any help would be really helpfull.

anyway, thank you for your job. this soft work flawlessly with homeassistant !

**Comment by billouetaudrey** [comment]
But where to you find the abrp token?

**Comment by aneantisor** [comment]
your can create it in your abrp app.

**Comment by billouetaudrey** [comment]
Ahhh yes found thanks

**Comment by billouetaudrey** [comment]
How you check/know it's work or not ?

**Comment by aneantisor** [comment]
it is totaly obvious,you cannot miss it.
On main screen, you will get a blue icon showing a batterie with signal.

**Comment by billouetaudrey** [comment]
I imagine you talk on ABRP? Can you show me a screenshot?
Because I see nothing. Maybe because as you say, abrp token not working without editing the py file

**Comment by aneantisor** [comment]
![Screenshot_2025-01-08-18-35-29-235_com iternio abrpapp-edit](https://github.com/user-attachments/assets/c241a32d-a235-4d4e-a69d-b241716e2720)

**Comment by billouetaudrey** [comment]
Yes so not working for me, need to investigate 

Thanks very much

**Comment by billouetaudrey** [comment]
This is my error : 

`2025-01-09T15:51:57.383192584Z            ^^^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383194048Z   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
2025-01-09T15:51:57.383195706Z     raise retry_exc.reraise()
2025-01-09T15:51:57.383197181Z           ^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383199801Z   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
2025-01-09T15:51:57.383201681Z     raise self.last_attempt.result()
2025-01-09T15:51:57.383203181Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383204660Z   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
2025-01-09T15:51:57.383206452Z     return self.__get_result()
2025-01-09T15:51:57.383207908Z            ^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383209426Z   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2025-01-09T15:51:57.383211095Z     raise self._exception
2025-01-09T15:51:57.383212611Z   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
2025-01-09T15:51:57.383214281Z     result = await fn(*args, **kwargs)
2025-01-09T15:51:57.383215802Z              ^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383217364Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 130, in execute_api_call_with_event_id_inner
2025-01-09T15:51:57.383219299Z     return await self.__execute_api_call(
2025-01-09T15:51:57.383220833Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383222362Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 107, in __execute_api_call
2025-01-09T15:51:57.383224138Z     return await self.__deserialize(req, response, out_type, allow_null_body)
2025-01-09T15:51:57.383225779Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-01-09T15:51:57.383227474Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 200, in __deserialize
2025-01-09T15:51:57.383229420Z     raise se
2025-01-09T15:51:57.383230964Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 167, in __deserialize
2025-01-09T15:51:57.383232818Z     raise SaicApiRetryException(error_message, event_id=event_id, return_code=return_code)`

**Comment by billouetaudrey** [comment]
I add my VIN, but nothing new on ABRP, do I need pro version? thanks

**Comment by aneantisor** [comment]
No need for pro version.

**Comment by billouetaudrey** [comment]
You use docker too ?
I try both and not working for me. I certainly do something wrong

**Comment by nanomad** [comment]
> This is my error :
> 
> ```
> 2025-01-09T15:51:57.383192584Z            ^^^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383194048Z   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
> 2025-01-09T15:51:57.383195706Z     raise retry_exc.reraise()
> 2025-01-09T15:51:57.383197181Z           ^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383199801Z   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
> 2025-01-09T15:51:57.383201681Z     raise self.last_attempt.result()
> 2025-01-09T15:51:57.383203181Z           ^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383204660Z   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
> 2025-01-09T15:51:57.383206452Z     return self.__get_result()
> 2025-01-09T15:51:57.383207908Z            ^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383209426Z   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
> 2025-01-09T15:51:57.383211095Z     raise self._exception
> 2025-01-09T15:51:57.383212611Z   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
> 2025-01-09T15:51:57.383214281Z     result = await fn(*args, **kwargs)
> 2025-01-09T15:51:57.383215802Z              ^^^^^^^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383217364Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 130, in execute_api_call_with_event_id_inner
> 2025-01-09T15:51:57.383219299Z     return await self.__execute_api_call(
> 2025-01-09T15:51:57.383220833Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383222362Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 107, in __execute_api_call
> 2025-01-09T15:51:57.383224138Z     return await self.__deserialize(req, response, out_type, allow_null_body)
> 2025-01-09T15:51:57.383225779Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 2025-01-09T15:51:57.383227474Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 200, in __deserialize
> 2025-01-09T15:51:57.383229420Z     raise se
> 2025-01-09T15:51:57.383230964Z   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 167, in __deserialize
> 2025-01-09T15:51:57.383232818Z     raise SaicApiRetryException(error_message, event_id=event_id, return_code=return_code)```
> ```

Please post the whole log, but  this seems like an error on MG side not ABRP

**Comment by billouetaudrey** [comment]
I have same error if I don't add the VIN

**Comment by nanomad** [comment]
Either post the full log or there's nothing much that can be done

**Comment by billouetaudrey** [comment]
Thanks 
[saic-mqtt-gateway_logs.txt](https://github.com/user-attachments/files/18377892/saic-mqtt-gateway_logs.txt)

**Comment by nanomad** [comment]
I can see a bunch of errors related to the state of the API on MG side:
- Notification list not responding properly
- You trying to lock the car while the car itself was still in READY mode. Keep in mind there are limitations on when we can remote-close the car (usually it can be done only if it has been opened remotely as well).

For ABRP, the sintax is VIN=TOKEN, e.g. LSJXXXXXXX=TOKENFROMABRP

**Comment by billouetaudrey** [comment]
```
billou@billou-serveur:~/Téléchargements/Serveur/Local/saic-python-mqtt-gateway$ docker-compose up
Creating saic-mqtt-gateway ... done
Attaching to saic-mqtt-gateway
saic-mqtt-gateway    | 2025-01-11 14:09:52,393 [  INFO  ] Fetching vehicle list - __main__
saic-mqtt-gateway    | 2025-01-11 14:09:52,454 [  INFO  ] Registering for ['ALARM_TYPE_VEHICLE_FAULT', 'ALARM_TYPE_GEOFENCE', 'ALARM_TYPE_VEHICLE_START'] messages. vin=*** - __main__
saic-mqtt-gateway    | 2025-01-11 14:09:52,540 [  INFO  ] Registered for ['ALARM_TYPE_VEHICLE_FAULT', 'ALARM_TYPE_GEOFENCE', 'ALARM_TYPE_VEHICLE_START'] messages. vin=*** - __main__
saic-mqtt-gateway    | 2025-01-11 14:09:52,688 [  INFO  ] Adding job tentatively -- it will be properly scheduled when the scheduler starts - apscheduler.scheduler
saic-mqtt-gateway    | 2025-01-11 14:09:52,689 [  INFO  ] [CONNECTION MADE] - gmqtt.mqtt.protocol
saic-mqtt-gateway    | 2025-01-11 14:09:52,695 [  INFO  ] Connected to MQTT broker - publisher.mqtt_publisher
saic-mqtt-gateway    | 2025-01-11 14:09:52,697 [  INFO  ] [SEND SUB] 1 [b'saic/billouetaudrey@gmail.com/vehicles/+/+/+/set'] - gmqtt.mqtt.package
saic-mqtt-gateway    | 2025-01-11 14:09:52,697 [  INFO  ] [SEND SUB] 2 [b'saic/billouetaudrey@gmail.com/vehicles/+/+/+/+/set'] - gmqtt.mqtt.package
saic-mqtt-gateway    | 2025-01-11 14:09:52,698 [  INFO  ] [SEND SUB] 3 [b'saic/billouetaudrey@gmail.com/vehicles/+/refresh/mode/set'] - gmqtt.mqtt.package
saic-mqtt-gateway    | 2025-01-11 14:09:52,698 [  INFO  ] [SEND SUB] 4 [b'saic/billouetaudrey@gmail.com/vehicles/+/refresh/period/+/set'] - gmqtt.mqtt.package
saic-mqtt-gateway    | 2025-01-11 14:09:52,700 [  INFO  ] Added job "Check for new messages" to job store "default" - apscheduler.scheduler
saic-mqtt-gateway    | 2025-01-11 14:09:52,700 [  INFO  ] Scheduler started - apscheduler.scheduler
saic-mqtt-gateway    | 2025-01-11 14:09:52,701 [  INFO  ] Publishing vehicle info to MQTT - vehicle
saic-mqtt-gateway    | 2025-01-11 14:09:52,706 [  INFO  ] [SUBACK] 1 (0,) - gmqtt
saic-mqtt-gateway    | 2025-01-11 14:09:52,706 [  INFO  ] [SUBACK] 2 (0,) - gmqtt
saic-mqtt-gateway    | 2025-01-11 14:09:52,706 [  INFO  ] [SUBACK] 3 (0,) - gmqtt
saic-mqtt-gateway    | 2025-01-11 14:09:52,706 [  INFO  ] [SUBACK] 4 (0,) - gmqtt
saic-mqtt-gateway    | 2025-01-11 14:10:02,718 [  INFO  ] Setting active query interval in vehicle handler for VIN *** to 0:00:30 - vehicle
saic-mqtt-gateway    | 2025-01-11 14:10:02,719 [  INFO  ] Setting after shutdown query interval in vehicle handler for VIN *** to 0:02:00 - vehicle
saic-mqtt-gateway    | 2025-01-11 14:10:02,719 [  INFO  ] Setting inactive query interval in vehicle handler for VIN *** to 1 day, 0:00:00 - vehicle
saic-mqtt-gateway    | 2025-01-11 14:10:02,719 [  INFO  ] Updating remote AC temperature to 22 - vehicle
saic-mqtt-gateway    | 2025-01-11 14:10:02,719 [  INFO  ] Setting refresh mode to periodic due to initial gateway startup from an invalid state RefreshMode.OFF - vehicle
saic-mqtt-gateway    | 2025-01-11 14:10:33,567 [ ERROR  ] handle_vehicle loop failed during SAIC API call - handlers.vehicle
saic-mqtt-gateway    | Traceback (most recent call last):
saic-mqtt-gateway    |   File "/usr/src/app/handlers/vehicle.py", line 97, in handle_vehicle
saic-mqtt-gateway    |     await self.__polling()
saic-mqtt-gateway    |   File "/usr/src/app/handlers/vehicle.py", line 124, in __polling
saic-mqtt-gateway    |     vehicle_status = await self.update_vehicle_status()
saic-mqtt-gateway    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/src/app/handlers/vehicle.py", line 181, in update_vehicle_status
saic-mqtt-gateway    |     vehicle_status_response = await self.saic_api.get_vehicle_status(self.vin_info.vin)
saic-mqtt-gateway    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/vehicle/__init__.py", line 15, in get_vehicle_status
saic-mqtt-gateway    |     return await self.execute_api_call_with_event_id(
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 139, in execute_api_call_with_event_id
saic-mqtt-gateway    |     return await execute_api_call_with_event_id_inner(event_id='0')
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
saic-mqtt-gateway    |     return await copy(fn, *args, **kwargs)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
saic-mqtt-gateway    |     do = await self.iter(retry_state=retry_state)
saic-mqtt-gateway    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
saic-mqtt-gateway    |     result = await action(retry_state)
saic-mqtt-gateway    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
saic-mqtt-gateway    |     return call(*args, **kwargs)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
saic-mqtt-gateway    |     raise retry_exc.reraise()
saic-mqtt-gateway    |           ^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
saic-mqtt-gateway    |     raise self.last_attempt.result()
saic-mqtt-gateway    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
saic-mqtt-gateway    |     return self.__get_result()
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
saic-mqtt-gateway    |     raise self._exception
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
saic-mqtt-gateway    |     result = await fn(*args, **kwargs)
saic-mqtt-gateway    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 130, in execute_api_call_with_event_id_inner
saic-mqtt-gateway    |     return await self.__execute_api_call(
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 107, in __execute_api_call
saic-mqtt-gateway    |     return await self.__deserialize(req, response, out_type, allow_null_body)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 200, in __deserialize
saic-mqtt-gateway    |     raise se
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 167, in __deserialize
saic-mqtt-gateway    |     raise SaicApiRetryException(error_message, event_id=event_id, return_code=return_code)
saic-mqtt-gateway    | saic_ismart_client_ng.exceptions.SaicApiRetryException: return code: 4, message: The remote control instruction failed, please try again later., event_id: 1552812924
saic-mqtt-gateway    | 2025-01-11 14:10:52,690 [  INFO  ] Running job "Check for new messages (trigger: interval[0:01:00], next run at: 2025-01-11 14:11:52 UTC)" (scheduled at 2025-01-11 14:10:52.688562+00:00) - apscheduler.executors.default
saic-mqtt-gateway    | 2025-01-11 14:10:53,342 [  INFO  ] Job "Check for new messages (trigger: interval[0:01:00], next run at: 2025-01-11 14:11:52 UTC)" executed successfully - apscheduler.executors.default
```

Dunno what to do :'(

**Comment by billouetaudrey** [comment]
Working now, dunno why
Thanks 😘😘😘
