### ISSUE TITLE
Client not authenticated, please call login first

### ISSUE THREAD

**Issue by bj00rn** [SAIC-iSmart-API/saic-python-mqtt-gateway#281]
Getting erroe `Client not authenticated, please call login first` when trying to force update from home assistant. Gateway does not seem to recover after this unless it is restarted manually.

Seems to happen after the gateway has been logged out by another client on my phone.

Im running a gateway cloned from master at https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/commit/eb9394756bd8de2be717d76ed7ee154d83f68c5a

```
saic-mqtt-gateway    | 2024-12-13 15:59:49,208 [  INFO  ] Updating vehicle status - __main__
saic-mqtt-gateway    | 2024-12-13 15:59:49,212 [ ERROR  ] NOT Retrying since we got a generic exception - saic_ismart_client_ng.api.base
saic-mqtt-gateway    | 2024-12-13 15:59:49,213 [ ERROR  ] handle_vehicle loop failed during SAIC API call - __main__
saic-mqtt-gateway    | Traceback (most recent call last):
saic-mqtt-gateway    |   File "/usr/src/app/./mqtt_gateway.py", line 96, in handle_vehicle
saic-mqtt-gateway    |     vehicle_status = await self.update_vehicle_status()
saic-mqtt-gateway    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/src/app/./mqtt_gateway.py", line 145, in update_vehicle_status
saic-mqtt-gateway    |     vehicle_status_response = await self.saic_api.get_vehicle_status(self.vin_info.vin)
saic-mqtt-gateway    |                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/vehicle/__init__.py", line 15, in get_vehicle_status
saic-mqtt-gateway    |     return await self.execute_api_call_with_event_id(
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 124, in execute_api_call_with_event_id
saic-mqtt-gateway    |     return await execute_api_call_with_event_id_inner(event_id='0')
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
saic-mqtt-gateway    |     return await copy(fn, *args, **kwargs)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
saic-mqtt-gateway    |     do = await self.iter(retry_state=retry_state)
saic-mqtt-gateway    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
saic-mqtt-gateway    |     result = await action(retry_state)
saic-mqtt-gateway    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
saic-mqtt-gateway    |     return call(*args, **kwargs)
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 398, in <lambda>
saic-mqtt-gateway    |     self._add_action_func(lambda rs: rs.outcome.result())
saic-mqtt-gateway    |                                      ^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
saic-mqtt-gateway    |     return self.__get_result()
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
saic-mqtt-gateway    |     raise self._exception
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
saic-mqtt-gateway    |     result = await fn(*args, **kwargs)
saic-mqtt-gateway    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 115, in execute_api_call_with_event_id_inner
saic-mqtt-gateway    |     return await self.execute_api_call(
saic-mqtt-gateway    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 91, in execute_api_call
saic-mqtt-gateway    |     response = await self.api_client.client.send(req)
saic-mqtt-gateway    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1646, in send
saic-mqtt-gateway    |     response = await self._send_handling_auth(
saic-mqtt-gateway    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
saic-mqtt-gateway    |     response = await self._send_handling_redirects(
saic-mqtt-gateway    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1709, in _send_handling_redirects
saic-mqtt-gateway    |     await hook(request)
saic-mqtt-gateway    |   File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/net/client/api.py", line 47, in __encrypt_request
saic-mqtt-gateway    |     raise SaicApiException("Client not authenticated, please call login first")
saic-mqtt-gateway    | saic_ismart_client_ng.exceptions.SaicApiException: Client not authenticated, please call login first
saic-mqtt-gateway    | 2024-12-13 15:59:49,218 [ DEBUG  ] Publishing Home Assistant discovery messages - integrations.home_assistant.discovery
saic-mqtt-gateway    | 2024-12-13 15:59:49,311 [ DEBUG  ] Completed publishing Home Assistant discovery messages - integrations.home_assistant.discovery
saic-mqtt-gateway    | 2024-12-13 15:59:49,312 [ DEBUG  ] Gateway failed refresh previously. Should refresh: False - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:49,314 [WARNING ] Executing <Task pending name='handle_vehicle_LSJW74095NZ115187' coro=<VehicleHandler.handle_vehicle() running at /usr/src/app/./mqtt_gateway.py:133> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:449> cb=[_wait.<locals>._on_completion() at /usr/local/lib/python3.12/asyncio/tasks.py:534] created at /usr/local/lib/python3.12/asyncio/tasks.py:420> took 0.107 seconds - asyncio
saic-mqtt-gateway    | 2024-12-13 15:59:50,315 [ DEBUG  ] Gateway failed refresh previously. Should refresh: False - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:51,318 [ DEBUG  ] Gateway failed refresh previously. Should refresh: False - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:52,320 [ DEBUG  ] Gateway failed refresh previously. Should refresh: False - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:52,413 [  INFO  ] Setting refresh mode to force due to MQTT direct set refresh mode command execution - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:52,414 [ DEBUG  ] Refresh mode set to force due to MQTT direct set refresh mode command execution - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:53,323 [  INFO  ] Setting refresh mode to periodic due to restoring of previous refresh mode after a FORCE execution - vehicle
saic-mqtt-gateway    | 2024-12-13 15:59:53,323 [ DEBUG  ] Refresh mode set to periodic due to restoring of previous refresh mode after a FORCE execution - vehicle
```

**Comment by nanomad** [comment]
Hi @bj00rn Could you test with the develop branch?

**Comment by bj00rn** [comment]
I believe it works much better with latest v7. Can we expect a new release soon?

**Comment by nanomad** [comment]
Yes :)
