### ISSUE TITLE
[ ERROR  ] Error while fetching a message from the SAIC API, please open the app and clear them, then report this as a bug

### ISSUE THREAD

**Issue by Tonno87** [SAIC-iSmart-API/saic-python-mqtt-gateway#287]
Getting an error with 0.7.0.-RC9 and RC13.

Found this error after creating a second account in the iSmart App. Can't say if this was already there before the update came out.

```
File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 194, in __deserialize
    raise se
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 191, in __deserialize
    raise SaicApiException(f"Failed to deserialize response, missing 'data' field: {response.text}")
saic_ismart_client_ng.exceptions.SaicApiException: Failed to deserialize response, missing 'data' field: {"code":0,"message":"success"}
2024-12-18 17:25:21,839 [ ERROR  ] Error while fetching a message from the SAIC API, please open the app and clear them, then report this as a bug. - handlers.message
Traceback (most recent call last):
  File "/usr/src/app/handlers/message.py", line 78, in __get_all_alarm_messages
    message_list = await self.saicapi.get_alarm_list(page_num=idx, page_size=1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/message/__init__.py", line 9, in get_alarm_list
    return await self.get_message_list(page_num=page_num, page_size=page_size, message_group='ALARM')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/message/__init__.py", line 18, in get_message_list
    return await self.execute_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 85, in execute_api_call
    raise e
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 75, in execute_api_call
    return await self.__execute_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 104, in __execute_api_call
    return await self.__deserialize(req, response, out_type)


```

**Comment by nanomad** [comment]
Interesting, where you using the "secondary" account by any chance? Or did you just add the second account to your main one?

**Comment by Tonno87** [comment]
I created a second account with the app and authorized it with the main account, after that i restarted the gateway and it shows the error above.

Now the error is gone after deleting all messages in both accounts.

[logs-1.txt](https://github.com/user-attachments/files/18222611/logs-1.txt)

**Comment by nanomad** [comment]
@Tonno87 Fix released in 0.7.1

**Comment by electricmax** [comment]
Hi, as I understand this issue is considered as to be fixed already.

Actually, I ran into the same log output:

[log_saic_phython_mqtt.txt](https://github.com/user-attachments/files/18506556/log_saic_phython_mqtt.txt)

I´ve already cleared the messages in the app using all accounts (account for smartphone app and linked account for Docker Container with saic-python-mqtt-gateway running).

Any ideas?

**Comment by electricmax** [comment]
Hi again,

Still running into this problem.

2025-01-30 09:57:14,518 [ ERROR  ] Error while fetching a message from the SAIC API, please open the app and clear them, then report this as a bug. - handlers.message
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 76, in execute_api_call
    return await self.__execute_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/api/base.py", line 106, in __execute_api_call
    response = await self.__api_client.send(req)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/saic_ismart_client_ng/net/client/__init__.py", line 35, in send
    return await self.__client.send(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1674, in send
    response = await self._send_handling_auth(

I´m not able to reopen this issue.
Could this be done by one of the participants or @nanomad himself?

I use this API for integrating charging of my MG5 into smarthome.

Thank you.

**Comment by nanomad** [comment]
> httpcore.ConnectTimeout

Nothing we can do about this, the MG server is timing out when requesting messages.

**Comment by electricmax** [comment]
It´s clear that if there is a timeout nothing can be done at the client side.
But why does the script stop working instead of working properly a soon it get´s an answer from the SAIC API during one of the following intervals.

Every time the script is running in a timeout - I have to restart die script.
