### ISSUE TITLE
Struggle to get it working

### ISSUE THREAD

**Issue by michpas** [SAIC-iSmart-API/saic-python-mqtt-gateway#34]
I use my phone number to login in the app; so have used +316xxxxxxxx as SAIC_user in HA config
In HA I get the following log error for 'SAIC MQTT Gateway Python". 

Can't figure out why this is not working. Any help would be highly appreciated.

Exception in thread Thread-1 (_thread_main):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
2023-07-13 23:59:40,155 Starting new HTTPS connection (1): tap-eu.soimt.com:443
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3039, in _packet_handle
    return self._handle_connack()
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 3138, in _handle_connack
    on_connect(
  File "/usr/src/app/mqtt_publisher.py", line 51, in __on_connect
    self.client.subscribe(f'{basic_topic}/refresh/mode/set')
  File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1491, in subscribe
    raise ValueError('Invalid subscription filter.')
ValueError: Invalid subscription filter.
2023-07-13 23:59:40,643 https://tap-eu.soimt.com:443 "POST /TAP.Web/ota.mp HTTP/1.1" 200 None
2023-07-13 23:59:40,656 MqttGateway crashed due to SaicApiException
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 383, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 117, in login
    raise SaicApiException(login_response_message.body.error_message.decode(),
saic_ismart_client.saic_api.SaicApiException: return code: 15011, message: The account is not registered.
return code: 15011, message: The account is not registered.

**Comment by tisoft** [comment]
The format for phone numbers for the European and Australien API endpoints is:

316-1234567

Country Code `-` phone number

No leading zeros.

**Comment by michpas** [comment]
Thanks. Good to know.
your 316-1234567 didn't work, but then I tried 31-61234567 which worked !  

Thanks
