### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by ifilgud** [SAIC-iSmart-API/saic-python-mqtt-gateway#89]
Hi!

I'm trying to manually run the mqtt gateway from a python venv and I'm getting this error:

2023-09-04 09:20:35,176 Connected to MQTT broker
Traceback (most recent call last):
  File "/home/pi/saic-python-mqtt-gateway/./mqtt_gateway.py", line 589, in <module>
    mqtt_gateway.run()
  File "/home/pi/saic-python-mqtt-gateway/./mqtt_gateway.py", line 269, in run
    login_response_message = self.saic_api.login()
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/saic_ismart_client/saic_api.py", line 113, in login
    login_request_hex = self.message_v1_1_coder.encode_request(login_request_message)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/saic_ismart_client/ota_v1_1/Message.py", line 10, in encode_request
    return super().encode_request(message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/saic_ismart_client/common_model.py", line 393, in encode_request
    application_data_bytes = self.get_application_data_bytes(message.application_data, self.asn1_tool_uper)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/saic_ismart_client/common_model.py", line 380, in get_application_data_bytes
    application_data_bytes = asn1_tool.encode(application_data.asn_type, application_data.get_data())
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/compiler.py", line 137, in encode
    type_.check_types(data)
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/compiler.py", line 102, in check_types
    return self.type_checker.encode(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 311, in encode
    raise e
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 307, in encode
    self._type.encode(data)
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 142, in encode
    self.encode_members(data)
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 154, in encode_members
    raise e
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 150, in encode_members
    member.encode(data[name])
  File "/srv/homeassistant/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 124, in encode
    raise EncodeError(
asn1tools.codecs.EncodeError: MPUserLoggingInReq.password: Expected data of type str, but got 900.

I don't know what is happening, any clue please? Is it a bug or maybe I'm missing something?
I realised that the requirements.txt file points to an old Saic Api Client module (1.4.9). With that one I just get a password error, pointing to the newest (1.6.0) I get this error.

Of course the login details are ok when using the old lib. The same I use for MG iSmart App

Thanks in advance!

**Comment by tosate** [comment]
This seems to be the same as #86 
Try to use a VENV with PY3.10.

**Comment by ifilgud** [comment]
I already tried on 3.10 but the issue you linked mentions to use saic client 1.5.0. I will try that

**Comment by ifilgud** [comment]
Ok, after some tests, it works if I remove the & from the password, and it only works with lib up to 1.5.0. With 1.6.0 I get error as above.

Thanks for the help!

Maybe this issue can be used to try to give support to special characters in passwords

**Comment by tosate** [comment]
The ampersand is a special character in your shell that needs to be escaped. [Have a look here](https://stackoverflow.com/questions/41012216/why-cant-i-use-in-python-command-line)
