### ISSUE TITLE
Won't work - has python updated?

### ISSUE THREAD

**Issue by saxon-viking** [SAIC-iSmart-API/saic-python-mqtt-gateway#93]
Hi,
This was working ok on my HA. I went on holiday, now I'm back I noticed an error on the MG4 info. I checked and the integration starts, but then fails. Has python updated? Any ideas what it might be please? This was a really good way to monitor the car. I have an HA VM running on Proxmox. The Java version won't even start. Everything else is fine

`2023-09-22 19:46:28,730 Connected to MQTT broker
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 589, in <module>
    mqtt_gateway.run()
  File "/usr/src/app/./mqtt_gateway.py", line 269, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 120, in login
    self.message_v1_1_coder.decode_response(login_response_hex, login_response_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/ota_v1_1/Message.py", line 13, in decode_response
    super().decode_response(message, decoded_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/common_model.py", line 400, in decode_response
    message_body_dict = self.asn1_tool_uper.decode(message_body.asn_type, dispatcher_message_bytes)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/compiler.py", line 167, in decode
    decoded = type_.decode(data)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 500, in decode
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 496, in decode
    return self._type.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 830, in decode
    decoded = self.decode_root(decoder)`

**Comment by tosate** [comment]
Please have a look at #86 
There might be something wrong with saic-ismart-client version 1.6.0. I'll have to investigate to reproduce the error.

**Comment by saxon-viking** [comment]
Thanks, it looks exactly like that. We changed the password after reading the previous and took out the special characters. Now it's working again. Thanks!
