### ISSUE TITLE
mpdispatcherbody.uid: out of Date bist 

### ISSUE THREAD

**Issue by kohbi** [SAIC-iSmart-API/saic-python-mqtt-gateway#94]
hey, my mqtt Gateway is Not Working 
I get this error . Can you help ? 

"/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 830, in decode
    decoded = self.decode_root(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 848, in decode_root
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 844, in decode_root
    value = member.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 107, in decode
    value = decoder.read_non_negative_binary_integer(self.bits_per_character)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 449, in read_non_negative_binary_integer
    raise OutOfDataError(self.number_of_read_bits())
asn1tools.codecs.OutOfDataError: MPDispatcherBody.uid: out of data (At bit offset: 58)

**Comment by tosate** [comment]
Please have a look at #86 
There might be something wrong with saic-ismart-client version 1.6.0. I'll have to investigate to reproduce the error.

**Comment by jomach** [comment]
Same issue here. https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/issues/35

**Comment by sh4rks** [comment]
Same issue for me

2023-10-11 13:33:36,826 A/C will be switched on
2023-10-11 13:33:37,005 0 messages received
2023-10-11 13:33:52,950 Error while processing MQTT message: MPDispatcherBody.token: out of data (At bit offset: 371)
Traceback (most recent call last):
  File "/usr/src/app/mqtt_publisher.py", line 70, in __on_message
    self.__on_message_real(client, userdata, msg)
  File "/usr/src/app/mqtt_publisher.py", line 91, in __on_message_real
    self.on_mqtt_command_received(vin, msg)
  File "/usr/src/app/./mqtt_gateway.py", line 316, in __on_mqtt_command_received
    vehicle_handler.handle_mqtt_command(msg)
  File "/usr/src/app/./mqtt_gateway.py", line 181, in handle_mqtt_command
    self.saic_api.start_ac(self.vin_info, temperature_idx=self.vehicle_state.get_ac_temperature_idx())
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 277, in start_ac
    return self.control_climate(vin_info, fan_speed=2, ac_on=None, temperature_idx=temperature_idx)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 352, in control_climate
    return self.send_vehicle_ctrl_cmd_with_retry(vin_info, b'\x06', rcv_params, True)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 439, in send_vehicle_ctrl_cmd_with_retry
    return self.handle_retry(
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 458, in handle_retry
    return self.__handle_retry_with_app_data(func, vin_info=vin_info, max_retries=max_retries)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 510, in __handle_retry_with_app_data
    rsp_msg = func(vin_info, rsp_msg.body.event_id)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 539, in __send_vehicle_control_command
    self.message_V2_1_coder.decode_response(vehicle_control_cmd_rsp_msg_hex, vehicle_control_cmd_rsp_msg)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/ota_v2_1/Message.py", line 12, in decode_response
    return super().decode_response(message, decoded_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/common_model.py", line 482, in decode_response
    message_body_dict = self.asn1_tool_uper.decode('MPDispatcherBody', dispatcher_message_bytes)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/compiler.py", line 167, in decode
    decoded = type_.decode(data)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 500, in decode
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 496, in decode
    return self._type.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 830, in decode
    decoded = self.decode_root(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 848, in decode_root
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 844, in decode_root
    value = member.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 107, in decode
    value = decoder.read_non_negative_binary_integer(self.bits_per_character)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 449, in read_non_negative_binary_integer
    raise OutOfDataError(self.number_of_read_bits())
asn1tools.codecs.OutOfDataError: MPDispatcherBody.token: out of data (At bit offset: 371)

**Comment by jomach** [comment]
@tosate Just installed again the add on on hass and I get the same error

**Comment by jomach** [comment]
2023-10-18 18:14:35,908 [  INFO  ] Connected to MQTT broker - mqtt_publisher
2023-10-18 18:14:35,915 [  INFO  ] Scheduler started - apscheduler.scheduler
Traceback (most recent call last):
  File "/usr/src/app/./mqtt_gateway.py", line 712, in <module>
    asyncio.run(mqtt_gateway.run(), debug=debug_log_enabled())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/src/app/./mqtt_gateway.py", line 301, in run
    login_response_message = self.saic_api.login()
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 120, in login
    self.message_v1_1_coder.decode_response(login_response_hex, login_response_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/ota_v1_1/Message.py", line 13, in decode_response
    super().decode_response(message, decoded_message)
  File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/common_model.py", line 436, in decode_response
    message_body_dict = self.asn1_tool_uper.decode(message_body.asn_type, dispatcher_message_bytes)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/compiler.py", line 167, in decode
    decoded = type_.decode(data)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 500, in decode
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 496, in decode
    return self._type.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 830, in decode
    decoded = self.decode_root(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 848, in decode_root
    raise e
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 844, in decode_root
    value = member.decode(decoder)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/uper.py", line 107, in decode
    value = decoder.read_non_negative_binary_integer(self.bits_per_character)
  File "/usr/local/lib/python3.10/site-packages/asn1tools/codecs/per.py", line 449, in read_non_negative_binary_integer
    raise OutOfDataError(self.number_of_read_bits())
asn1tools.codecs.OutOfDataError: MPDispatcherBody.uid: out of data (At bit offset: 58)

**Comment by tosate** [comment]
Too bad. Can you please provide the raw response?
It is published under saic/<applicationID>_<applicationDataProtocolVersion>/raw/response

**Comment by jomach** [comment]
ps: my password is correct ! I copied and pasted it !

**Comment by tosate** [comment]
A raw response is something like
`1012E211B0035333434333437313336323530363732FFFD83060C183060C183060C183060C183060C183060C183060C183060C183060C18B060C183060C183768DDBB768C5BB76CC59325AD5830CAB5A37C8E16E1CCE582D738DC30CB8F13870D5BB462DD9346AC584CA72ABC868C1CB1A13983460E5A3703C97C3D5B90320FC400000004000000003280A00104F2630903A3AB09030BD34B7B7329061D4103A3937B8383790333932B8BAB2B73A3297102832B91036309039B4B1BAB932BD3D30903232B6103B32B4B1B7B63796103ABA34B634BD3D30B9329036309031B434B0BB32903334B9B4B1B0903832B91030BB3B34B0B9329034B6103B32B4B1B7B6379032903934B83937BB30B932903237B8379030BB32B91039B832B73A379034B61036B7BA37B93297141B98948`

The decoding of this message into an object representation fails. The example you have posted originates from a successful decoding.

Try to delete all topics with the pattern `saic/<applicationID>_<applicationDataProtocolVersion>/raw/response`
Then run the application.
There should be one topic without `saic/<applicationID>_<applicationDataProtocolVersion>/json/response`

**Comment by jomach** [comment]
021D111000C00D82F60C183060C183060C183060C183060C183060C11EADFCB3E55DDD76DC38F461C9BE068DFD36E1D3B1763DFB5B3366E736666DDA306B91A337193162C39B0B572C9AE362C71376989CB96B871B76395AB062CA6008D6000000000000040202468ACF1343530ECA864468ACF1342468ACF1342000000000100A757244A9B7B9393C96103A34329030B1B1B7BAB73A103430B9903132B2B7103637B1B5B2B21610383632B0B9B2903A393C9030B3B0B4B7103A37B6B7B93937BB9037B9103CB7BA9036B0BC903932B9B2BA103830B9B9BBB7B93210313C9031B634B1B5B4B7339071404E3337B933B2BA103830B9B9BBB7B93271404EB4B3103CB7BA903337B933B2BA1034BA170

**Comment by tosate** [comment]
{
    "applicationData": null,
    "body": {
        "applicationID": "501",
        "eventCreationTime": 1697645675,
        "messageID": 2,
        "applicationDataLength": 0,
        "applicationDataProtocolVersion": 513,
        "uid": "0000000000000000000000#secret",
        "token": "secret",
        "eventID": 0,
        "applicationDataEncoding": "perUnaligned",
        "testFlag": 2,
        "result": 15033,
        "errorMessage": "Sorry, the account has been locked, please try again tomorrow or you may reset password by clicking \u201cforget password\u201dif you forget it.",
        "iccID": "secret",
        "simInfo": "secret",
        "messageCounter": {
            "uplinkCounter": 1,
            "downlinkCounter": 1
        }
    },
    "header": {
        "protocolVersion": 17,
        "dispatcherMessageLength": 12,
        "dispatcherBodyEncoding": 0,
        "securityContext": 0
    }
}

**Comment by tosate** [comment]
I have to update the client library to fix the processing of this message. You should get your account unlocked.

**Comment by kohbi** [comment]
I
I Update to docker latest 0.4.3 … But Issue is present

**Comment by tosate** [comment]
Thanks for testing. Please update to the latest version!

**Comment by kohbi** [comment]
Hey, 

I changed Passwort two times … App Login pass…. But Gateway Logs this : 

 2023-10-19 12:41:52,402 [  INFO  ] Connected to MQTT broker - mqtt_publisher
 2023-10-19 12:41:52,434 [  INFO  ] Scheduler started - apscheduler.scheduler
 2023-10-19 12:41:53,112 [ DEBUG  ] Message length in bytes: 268.0 - saic_ismart_client.common_model
 2023-10-19 12:41:53,114 [ DEBUG  ] Protocol version: 17 - saic_ismart_client.common_model
 2023-10-19 12:41:53,114 [ DEBUG  ] Dispatcher message length: 12 - saic_ismart_client.common_model
 2023-10-19 12:41:53,114 [ DEBUG  ] Message size without header: 264.0 - saic_ismart_client.common_model
 2023-10-19 12:41:53,115 [ DEBUG  ] Dispatcher message bytes: 8 - saic_ismart_client.common_model
 2023-10-19 12:41:53,115 [ DEBUG  ] Calculated message size 264 does not match with header size information 8. Using calculated size. - saic_ismart_client.common_model
 2023-10-19 12:41:53,118 [ ERROR  ] MqttGateway crashed due to SaicApiException - __main__
 Traceback (most recent call last):
   File "/usr/src/app/./mqtt_gateway.py", line 301, in run
     login_response_message = self.saic_api.login()
   File "/usr/local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 122, in login
     raise SaicApiException(login_response_message.body.error_message,
 saic_ismart_client.exceptions.SaicApiException: return code: 15033, message: Sorry, the account has been locked, please try again tomorrow or you may reset password by clicking “forget password”if you forget it.
 2023-10-19 12:41:53,120 [ DEBUG  ] Looking for jobs to run - apscheduler.scheduler
 2023-10-19 12:41:53,121 [ DEBUG  ] No jobs; waiting until a job is added - apscheduler.scheduler
 return code: 15033, message: Sorry, the account has been locked, please try again tomorrow or you may reset password by clicking “forget password”if you forget it.

**Comment by tosate** [comment]
Do you use the Docker container or just the Python script?
Does your password contain an ampersand? Have a look at #97

**Comment by tosate** [comment]
I am running out of ideas. If you are running from a script or a docker compose file, make sure that there is no white space character behind your password.

**Comment by kohbi** [comment]
Now it works :) thx.

**Comment by jomach** [comment]
It works now. I changed the password and make sure I enter it correctly
