### ISSUE TITLE
MG ZS EV: Error with Door locking

### ISSUE THREAD

**Issue by bisscuitt** [SAIC-iSmart-API/saic-python-mqtt-gateway#96]
While I can successfully Unlock the doors on my MG ZS EV, there is an error when requesting the doors to be LOCKED:

```
2023-10-06 11:14:34,715 [  INFO  ] Vehicle LSJWXXXXXXXXXX will be locked - __main__
2023-10-06 11:14:34,908 [ DEBUG  ] application ID: 510, protocol version: 25857, message: The service is not available,please try again later~ result code: 6 - saic_ismart_client.saic_api
```

Currently using version `0.4.0-rc1` but same error when running from `main` branch. Please let me know what other information I can provide to help debug the issue.

**Comment by nanomad** [comment]
Does the official app support door locking for your specific model?

**Comment by InfectedSoap** [comment]
Same issue with Marvel R Luxary. I can unlock without issues but locking has always been broken for me across all versions of the gateway. 

If I switch over to the official MG iSMART app I can lock the car no problem. 

I get the same error message as @bisscuitt.

**Comment by bisscuitt** [comment]
I can confirm that the MG iSMART app on android allows me to lock the doors.

I need to lock the doors to enable the aircon from the app... which is why I really want the door lock to work so that I can create an automation in HA to turn on the aircon when needed.

I can confirm that this is still an issue on the latest master:
```
2024-01-04 11:43:36,270 [ ERROR  ] return code: 6, message: The service is not available,please try again later~ - __main__
Traceback (most recent call last):
  File "/home/bisscuitt/src/SAIC-iSmart-API/saic-python-mqtt-gateway/./mqtt_gateway.py", line 195, in handle_mqtt_command
    self.saic_api.lock_vehicle(self.vin_info)
  File "/home/bisscuitt/.local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 207, in lock_vehicle
    return self.send_vehicle_ctrl_cmd_with_retry(vin_info, b'\x01', rvc_params, False)
  File "/home/bisscuitt/.local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 439, in send_vehicle_ctrl_cmd_with_retry
    return self.handle_retry(
  File "/home/bisscuitt/.local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 460, in handle_retry
    return self.__handle_retry_without_app_data(func, vin_info=vin_info, max_retries=max_retries)
  File "/home/bisscuitt/.local/lib/python3.10/site-packages/saic_ismart_client/saic_api.py", line 483, in __handle_retry_without_app_data
    raise SaicApiException(rsp_msg.body.error_message.decode(),
saic_ismart_client.exceptions.SaicApiException: return code: 6, message: The service is not available,please try again later~
```

If there's any other info you need or things I can do to help work out what's not working I'd be happy to dig into it.

**Comment by sarakha63** [comment]
@nanomad 

I can confirm that door locking fails on whatever car.

I own a MG4 Luxury and a friend owns a ZS EV

I have deployed the gateway for both of us. And door locking always fails and is not related to an error on the app. I mean it always fails on the gateway and always succeed on ismart  in the same range of time

I will try to dig in the code as i'm used to do and report back if i find something. But i just noticed this issue and wanted to refer that with a lot of testing i can confirm what i said just above (always fails with the gateway, always succeed on ismart on the same range of time) . Didnt have time to dig yet

**Comment by nanomad** [comment]
Thanks for the report @sarakha63. If you want a hand in debugging it hit me on Telegram, the username is the same as on GH

**Comment by nanomad** [comment]
@sarakha63 Can you try with the gateway version 0.5.7? The docker image should be done in a few minutes

It was an error during the encoding of the Vehicle Control command

**Comment by sarakha63** [comment]
@nanomad 

Confirmes working on my MG4 too ;)

Gg
